version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      prisma:
        patterns:
          - "prisma"
          - "@prisma/*"
      aws-sdk:
        patterns:
          - "@aws-sdk/*"
      types:
        patterns:
          - "@types/*"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
